# Generated by Django 4.2.30 on 2026-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Expense title / description', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=12)),
                ('due_date', models.DateField(help_text='Deadline for this expense')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Priority level of the expense', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', help_text='Current status of the expense', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upcoming Expense',
                'verbose_name_plural': 'Upcoming Expenses',
                'db_table': 'upcoming_expenses',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
